name: mcdonalds_website_clone
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/image1.png
    - assets/images/image2.png
    - assets/images/image3.png
    - assets/images/image4.png
    - assets/images/image5.png
    - assets/images/image6.png
    - assets/images/mcdo_logo.png
    - assets/images/grid1.png
    - assets/images/grid2.png
    - assets/images/grid3.png
    - assets/images/grid4.png
    - assets/images/grid5.png
    - assets/images/grid6.png
